### ISSUE TITLE
SQLite3: panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by deluan** [sue445/plant_erd#210]
Hey, thanks for such a cool project. I'm having an issue while running it on my database, though:
```
$ plant_erd sqlite3 --database navidrome.db

panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/sue445/plant_erd/adapter/sqlite3.(*Adapter).getForeignKeys(0xc0000a8110, {0xc0000acb60?, 0x100512a3c?})
        /Users/runner/work/plant_erd/plant_erd/adapter/sqlite3/adapter.go:115 +0x3eb
github.com/sue445/plant_erd/adapter/sqlite3.(*Adapter).GetTable(0xc0000a8110, {0xc0000acb60, 0xc})
        /Users/runner/work/plant_erd/plant_erd/adapter/sqlite3/adapter.go:80 +0x454
github.com/sue445/plant_erd/lib.LoadSchema({0x1005b1e48, 0xc0000a8110})
        /Users/runner/work/plant_erd/plant_erd/lib/schema.go:17 +0x12c
main.main.func1(0xc00014a160?)
        /Users/runner/work/plant_erd/plant_erd/cmd/plant_erd/main.go:64 +0x86
github.com/urfave/cli.HandleAction({0x1004b0e20?, 0xc0000a2270?}, 0x7?)
        /Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.10/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x100516141, 0x7}, {0x0, 0x0}, {0xc000099910, 0x1, 0x1}, {0x10051f9c8, 0x19}, {0x0, ...}, ...}, ...)
        /Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.10/command.go:173 +0x65b
github.com/urfave/cli.(*App).Run(0xc000146000, {0xc0000b4000, 0x5, 0x5})
        /Users/runner/go/pkg/mod/github.com/urfave/cli@v1.22.10/app.go:277 +0x8c7
main.main()
        /Users/runner/work/plant_erd/plant_erd/cmd/plant_erd/main.go:213 +0x1132
```

This is the file I'm trying to read (no worries, data is dummy):
[navidrome.db.zip](https://github.com/sue445/plant_erd/files/10996574/navidrome.db.zip)

I'm using macOS amd64 and this happens with both the latest release 0.4.2 and building it from master.

Hopefully this is a simple fix :)

**Comment by sue445** [comment]
@deluan I fixed at #211 and published v0.4.3 🚀 
https://github.com/sue445/plant_erd/releases/tag/v0.4.3

I have confirmed that there are no errors in `navidrome.db`.

However, I'm not very familiar with sqlite3, so I'm not sure if this is the correct fix :sweat_smile:

So let me know if you find the output results to be incorrect.
